# Generated by Django 3.2.4 on 2021-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('cartype', models.CharField(max_length=255)),
                ('pickadd', models.TextField()),
                ('dropadd', models.TextField()),
                ('pickdateandtime', models.DateTimeField()),
            ],
        ),
    ]
